kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: api-framework
spec:
  displayName: API Framework
  owner:
    team: loft-admins
  quotas:
    project:
      count/virtualclusterinstances.active: '15'
    user:
      count/virtualclusterinstances: '4'
  allowedClusters:
    - name: loft-cluster
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: default-template
      isDefault: true
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: pull-request-vcluster
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: kuberay-volcano
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: argo-cd-vcluster
  requireTemplate: {}
  members:
    - kind: Team
      group: storage.loft.sh
      name: api-framework
      clusterRole: loft-management-project-user
  access:
    - name: loft-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      teams:
        - loft-admins
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
        - runners
      teams:
        - api-framework
  argoCD:
    enabled: true
    virtualClusterInstance: argocd
    namespace: argocd
    sso:
      enabled: true
      host: https://argocd-REPLACE_BASE_DOMAIN
      assignedRoles:
        - role:admin
  namespacePattern:
    virtualCluster: '{{.Values.loft.project}}-v-{{.Values.loft.name}}'
---
kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: auth-core
spec:
  displayName: Auth Core
  description: AuthN and AuthZ core components built on top of the API Framework.
  owner:
    team: loft-admins
  quotas:
    project:
      count/virtualclusterinstances.active: '20'
  allowedClusters:
    - name: '*'
  allowedTemplates:
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: default-template
      isDefault: true
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: vcluster-pro-template
  requireTemplate: {}
  members:
    - kind: Team
      group: storage.loft.sh
      name: auth-core
      clusterRole: loft-management-project-user
  access:
    - name: loft-admin-access
      verbs:
        - get
        - update
        - patch
        - delete
      subresources:
        - '*'
      teams:
        - loft-admins
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
        - runners
      teams:
        - auth-core
  argoCD:
    enabled: true
    cluster: loft-cluster
    namespace: argocd
    sso:
      enabled: true
      host: https://argocd-REPLACE_BASE_DOMAIN/
      assignedRoles:
        - role:admin
    project:
      enabled: true
      metadata: {}
---
kind: Project
apiVersion: management.loft.sh/v1
metadata:
  name: default
  annotations:
    loft.sh/project-namespace: p-default
spec:
  displayName: Default Project
  description: This is the default project
  quotas: {}
  allowedClusters:
    - name: '*'
  allowedRunners:
    - name: '*'
  allowedTemplates:
    - kind: SpaceTemplate
      group: storage.loft.sh
      name: '*'
    - kind: VirtualClusterTemplate
      group: storage.loft.sh
      name: '*'
    - kind: DevPodWorkspaceTemplate
      group: storage.loft.sh
      name: '*'
  requireTemplate:
    disabled: true
  members:
    - kind: User
      group: storage.loft.sh
      name: '*'
      clusterRole: loft-management-project-user
  access:
    - name: loft-access
      verbs:
        - get
      subresources:
        - members
        - clusters
        - templates
        - chartinfo
        - charts
        - runners
      users:
        - '*'
  argoCD:
    cluster: loft-cluster
    namespace: argocd
    sso:
      host: https://argocd-REPLACE_BASE_DOMAIN/
      assignedRoles:
        - role:admin
