apiVersion: apps/v1
kind: Deployment
metadata:
  name: breakout-test-vnode
  namespace: default
  labels:
    app: breakout-test-vnode
spec:
  selector:
    matchLabels:
      app: breakout-test-vnode
  template:
    metadata:
      labels:
        app: breakout-test-vnode
    spec:
      runtimeClassName: vnode
      containers:
        - name: breakout
          image: busybox
          command:
            - /bin/sh
          args:
            - '-c'
            - sleep 10000
          securityContext:
            privileged: true
      nodeSelector:
        kubernetes.io/hostname: kpi-w51
      hostNetwork: true
      hostPID: true
