apiVersion: management.loft.sh/v1
kind: ProjectSecret
metadata:
  name: argocd-notifications-secret
  namespace: p-api-framework
  labels:
    loft.sh/project-secret-name: argocd-notifications-secret
spec:
  displayName: argocd-notifications-secret
  data:
