kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: preview-template
  labels:
    patchType: non-versioned
spec:
  displayName: vCluster Preview Template
  template:
    metadata:
      labels:
        loft.sh/import-argocd: 'true'
      annotations:
        sleepmode.loft.sh/delete-after: '72000'
        loft.sh/require-ingress-authentication: 'true'
        sleepmode.loft.sh/sleep-after: '600'
        sleepmode.loft.sh/ignore-user-agents: 'argo*'
    objects: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: preview-hello-world-app
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-login-secret
        namespace: preview-hello-world-app
        labels:
          loft.sh/project-secret-name: ghcr-login-secret
      data:
        .dockerconfigjson: e30K
      type: kubernetes.io/dockerconfigjson
    access:
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.26.0
      values: |-
        sleepMode:
          enabled: true
          autoSleep:
            afterInactivity: "{{ .Values.sleepAfter }}m"
        external:
          platform:
            autoDelete:
              afterInactivity: 120000
        sync:
          toHost:
            ingresses:
              enabled: true
            secrets:
              all: true

        controlPlane:
          # Use an embedded managed etcd server instead of using the k3s default SQLite backend
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
        policies:
          limitRange:
            enabled: true
          podSecurityStandard: baseline
          resourceQuota:
            enabled: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      type: number
      options:
        - '30'
        - '45'
        - '60'
        - '120'
      defaultValue: '45'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      type: string
      options:
        - v1.33.2
        - v1.32.6
        - v1.31.10
        - v1.30.13
      defaultValue: v1.32.6
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
