apiVersion: v1
kind: Namespace
metadata:
  name: p-vcluster-flux-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-admin-access-key
  namespace: p-vcluster-flux-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    loft.sh/project-secret-name: demo-admin-access-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
  namespace: p-vcluster-flux-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    loft.sh/project-secret-name: ghcr-login-secret
type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vcluster-flux-demo
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interval: 5m0s
  url: https://github.com/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-flux-kustomize
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  interval: 1m
  retryInterval: 30s
  targetNamespace: p-vcluster-flux-demo
  sourceRef:
    kind: GitRepository
    name: vcluster-flux-demo
  path: "./vcluster-use-cases/flux/kustomize"
  prune: true
  timeout: 2m
  wait: true
  # important: this feature requires Flux 2.5+
  healthCheckExprs:
    - apiVersion: management.loft.sh/v1
      kind: VirtualClusterInstance
      failed: "status.conditions.filter(e, e.type == 'VirtualClusterReady').all(e, e.status == 'False')"
      current: "status.conditions.filter(e, e.type == 'VirtualClusterReady').all(e, e.status == 'True')"
