apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-gitops
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: vcluster-gitops
    repoURL: https://github.com/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
