apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-manifests
  namespace: argocd
  labels:
    eso.demos.loft.sh: eso
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}
    targetRevision: HEAD
    path: vcluster-use-cases/external-secrets-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: eso-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
