apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: argocd
  namespace: p-api-framework
spec:
  owner:
    team: loft-admins
  templateRef:
    name: argo-cd-vcluster
  clusterRef:
    cluster: loft-cluster
---
apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: api-framework-qa
  namespace: p-api-framework
spec:
  owner:
    team: api-framework
  templateRef:
    name: default-template
    version: 1.0.x
  clusterRef:
    cluster: loft-cluster
  parameters: |
    k8sVersion: v1.30.5
    env: 'qa'
