---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-database-connector
  namespace: vcluster-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    loft.sh/display-name: "MySQL DB Connector"
  labels:
    loft.sh/project-secret-name: database-connector
    loft.sh/connector-type: "shared-database"
type: Opaque
