apiVersion: management.loft.sh/v1
kind: App
metadata:
  name: argo-cd-cluster-application-set
spec:
  displayName: Argo CD Cluster Application Set
  owner:
    team: loft-admins
  recommendedApp:
    - virtualcluster
  defaultNamespace: argocd
  config:
    chart: {}
    manifests: |-
      apiVersion: demo.loft.sh/v1alpha1
      kind: ArgoCDWebhook
      metadata:
        name: "{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.project }}-webhooks"
        namespace: argocd
      spec:
        repoName: "{{ .Values.loft.clusterAnnotations.domainPrefix }}-app"
        virtualClusterNamespace: "{{ .Values.loft.virtualClusterNamespace }}"
      ---
      apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: vcluster-env-config
        namespace: argocd
      spec:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: "dev"
          - clusters:
              selector:
                matchLabels:
                  env: "qa"
          - clusters:
              selector:
                matchLabels:
                  env: "prod"
        template:
          metadata:
            # name is the name of the kubernetes cluster as selected by the spec above
            name: '{{ .Values.loft.clusterAnnotations.domainPrefix }}-app-{{`{{name}}`}}'
          spec:
            destination:
              # server is the url of the 
              server: '{{`{{server}}`}}'
              # metadata.labels.env is the value of the env label that is being used to select kubernetes clusters 
              # and used as sub-folder in the target git repository
              namespace: '{{ .Values.loft.clusterAnnotations.domainPrefix }}-app-{{`{{metadata.labels.env}}`}}'
            info:
              - name: GitHub Repo
                value: https://github.com/loft-demos/{{ .Values.loft.clusterAnnotations.domainPrefix }}-app/
            project: default
            source:
              path: 'k8s-manifests/{{`{{metadata.labels.env}}`}}/'
              repoURL: https://github.com/loft-demos/{{ .Values.loft.clusterAnnotations.domainPrefix }}-app.git
              targetRevision: main
            syncPolicy:
              automated:
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
