kind: App
apiVersion: management.loft.sh/v1
metadata:
  name: eso
spec:
  displayName: External Secrets Operator
  description: External Secrets Operator is a Kubernetes operator that integrates external secret management 
  recommendedApp:
    - cluster
  defaultNamespace: external-secrets
  icon: https://artifacthub.io/image/f23fb631-4a3c-46c0-bda1-7a048cabf10d@2x
  config:
    chart:
      name: external-secrets
      version: 0.10.3
      repoURL: https://charts.external-secrets.io/
    values: '{{ .Values.appValues }}'
  parameters:
    - variable: appValues
      label: Helm Values
      description: The helm values to use to deploy this chart.
      type: multiline
      defaultValue: |-
        server:
          ingress:
            enabled: true
            hosts:
            - my-domain.com
  versions:
    - icon: https://artifacthub.io/image/f23fb631-4a3c-46c0-bda1-7a048cabf10d@2x
      defaultNamespace: external-secrets
      config:
        chart:
          name: external-secrets
          version: 0.10.3
          repoURL: https://charts.external-secrets.io/
        values: '{{ .Values.appValues }}'
      parameters:
        - variable: appValues
          label: Helm Values
          description: The helm values to use to deploy this chart.
          type: multiline
          defaultValue: |-
            server:
              ingress:
                enabled: true
                hosts:
                - my-domain.com
      wait: true
      version: 0.10.3
  access:
    - verbs:
        - get
      users:
        - '*'
