# The Argo CD Application for bootstrapping the vCluster Add-ons Demo Use Case
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vcluster-add-ons-app
  namespace: argocd
  labels:
    pr.argocd.demos.loft.sh: bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/{REPLACE_ORG_NAME}/{REPLACE_REPO_NAME}
    targetRevision: HEAD
    path: vcluster-use-cases/argocd-vcluster-add-ons/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
