apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eso-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            eso: 'true'
  template:
    metadata:
      # name is the name of the kubernetes cluster as selected by the spec above
      name: 'eso-apps'
      labels:
        eso.demos.loft.sh: eso
    spec:
      destination:
        # server is the url of the cluster as selected by the spec above
        server: '{{server}}'
        namespace: argocd
      project: default
      source:
        repoURL: https://github.com/loft-demos/{REPLACE_REPO_NAME}
        targetRevision: HEAD
        path: vcluster-gitops/argocd/external-secrets-operator/apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 20s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 3m
