apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flux-operator-helm-app
  namespace: argocd
  labels:
    flux.demos.loft.sh: flux
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # server is the url of the cluster as selected by the spec above
    server: https://kubernetes.default.svc
    namespace: flux-system
  project: default
  source:
    chart: flux-operator
    repoURL: ghcr.io/controlplaneio-fluxcd/charts
    targetRevision: 0.24.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 20s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m
