apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtual-cluster-templates
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/loft-demos/zulu-app
    targetRevision: main
    path: vcluster-gitops/virtual-cluster-templates/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: loft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true