apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-provider-config
  namespace: crossplane-system
spec:
  credentials:
    secretRef:
      key: credentials
      name: github-provider-secret
      namespace: crossplane-system
    source: Secret
