apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: vcluster-b
  namespace: p-beta
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  displayName: vcluster-b
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    objects: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: curl-pod
        namespace: default
        annotations:
          sleepmode.loft.sh/exclude: 'true'
      spec:
        containers:
          - name: curl
            image: curlimages/curl:7.88.1
            command:
              - tail
              - '-f'
              - /dev/null
    pro: {}
    helmRelease:
      chart:
        name: vcluster
        version: 0.22.4
      values: |
        networking:
          resolveDNS:
            - service: svc-b/nginx-b
              target:
                vClusterService: alpha-v-vcluster-a/vcluster-a/svc-a/nginx-a
        sync:
          toHost:
            ingresses:
              enabled: true
        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            enabled: true
            embedded: true
        external:
          platform:
            autoSleep:
              afterInactivity: 34800
              autoWakeup:
                schedule: 30 7 * * 1-5
              schedule: 0 19 * * 1-5
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  clusterRef:
    cluster: loft-cluster
    namespace: beta-v-vcluster-b
    virtualCluster: vcluster-b
  networkPeer: true
