---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-login-secret
  namespace: eso-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    loft.sh/project-secret-name: ghcr-login-secret
data:
  .dockerconfigjson: e30K
type: kubernetes.io/dockerconfigjson
