apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: eso-vc
  namespace: p-default
spec:
  displayName: eso-vc
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.21.0-alpha.9
      values: |-
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          coredns:
            enabled: true
            embedded: true

        integrations:
          # ExternalSecrets reuses a host external secret operator and makes certain CRDs from it available inside the vCluster
          externalSecrets:
            # Enabled defines whether the external secret integration is enabled or not
            enabled: true
            # Webhook defines whether the host webhooks are reused or not
            webhook:
              enabled: true
            # Sync defines the syncing behavior for the integration
            sync:
              # ExternalSecrets defines whether to sync external secrets or not
              externalSecrets:
                enabled: true
              # Stores defines whether to sync stores or not
              stores:
                enabled: false
              # ClusterStores defines whether to sync cluster stores or not
              clusterStores:
                # Enabled defines if this option should be enabled.
                enabled: false
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  clusterRef:
    cluster: loft-cluster
    namespace: loft-default-v-eso-vc
    virtualCluster: eso-vc
