apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-manifests
  namespace: argocd
  labels:
    kyverno.demos.loft.sh: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/loft-demos/{REPLACE_REPO_NAME}
    targetRevision: HEAD
    path: vcluster-gitops/argocd/kyverno/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: eso-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
