name: create-vcluster

on:
  workflow_dispatch:
  
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  create-vcluster:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Show vCluster Version
        run: vcluster --version
      - name: Login to vCluster Platform instance
        env:
          VCLUSTER_PLATFORM_URL: ${{ secrets.VCLUSTER_PLATFORM_URL }}
          ACCESS_KEY: ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}
        run: vcluster platform login $VCLUSTER_PLATFORM_URL --access-key $ACCESS_KEY

      - id: create-vcluster
        run: |
          vcluster platform create vcluster $REPO_NAME --project default --recreate
