name: delete-old-repo-package

# on merge to main from pull request (recommended)
on:
  create:
  workflow_dispatch:
jobs:
  delete-old-repo-package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - id: delete-package
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.KM_PAT_DELETE_PACKAGES }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/loft-demos/packages/container/${{ github.event.repository.name }}
