name: Pull Request e2e Tests with vCluster
on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
    branches:
      - "main"
      
env:
  VCLUSTER_NAME: pr-${{ github.event.pull_request.number }}-${{ github.run_id }}
  
jobs:
  e2e:
    if: ${{ github.event.label.name == 'e2e' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Show vCluster Version
        run: vcluster --version
      - name: Login to vCluster Platform instance
        env:
          VCLUSTER_PLATFORM_URL: ${{ secrets.VCLUSTER_PLATFORM_URL }}
          ACCESS_KEY: ${{ secrets.VCLUSTER_PLATFORM_ACCESS_KEY }}
        run: vcluster platform login $VCLUSTER_PLATFORM_URL --access-key $ACCESS_KEY
      - name: Create PR Virtual Cluster
        run: vcluster platform create vcluster $VCLUSTER_NAME --project api-framework
      - name: List vCluster Namespaces
        run: kubectl get ns
      - name: Run Tests
        run: sleep 5
      - name: Delete PR Virtual Cluster
        run: vcluster platform delete vcluster $VCLUSTER_NAME --project api-framework
