name: replace-text

# on push to main
on:
  workflow_dispatch:
    inputs:
      vcluster_name:
        description: "Override default vCluster name which matches the repo name (minus `-app`)"
        required: false
        default: ""
      base_domain:
        description: "Base domain used to create example host names"
        required: true
        default: "us.demo.dev"
  push:
    branches:
      - main
    paths:
      - 'helm-chart/Chart.yaml'
env:
  REPO_NAME: ${{ github.event.repository.name }}
  ORG_NAME: ${{ github.repository_owner || 'loft-demos' }}
  BASE_DOMAIN: ${{ inputs.base_domain || 'us.demo.dev' }}

jobs:
  replace-text:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: set-vcluster-name
        id: set-vcluster-name
        run: |
          if [ -n "${{ inputs.vcluster_name }}" ]; then
            echo "VCLUSTER_NAME=${{ inputs.vcluster_name }}" >> "$GITHUB_ENV"
          else
            echo "VCLUSTER_NAME=$(echo "${REPO_NAME%-app}")" >> "$GITHUB_ENV"
          fi
          echo "vCluster name is $VCLUSTER_NAME"
      - uses: actions/checkout@v3
      - uses: flcdrg/replace-multiple-action@v2.0.148
        with:
          files: '**/*.yaml'
          find:  |
            [
              { "find": "{REPLACE_REPO_NAME}", "replace": "${{ env.REPO_NAME }}" },
              { "find": "{REPLACE_ORG_NAME}", "replace": "${{ env.ORG_NAME }}" },
              { "find": "{REPLACE_VCLUSTER_NAME}", "replace": "${{ env.VCLUSTER_NAME }}" },
              { "find": "{REPLACE_BASE_DOMAIN}", "replace": "${{ env.BASE_DOMAIN }}" }
            ]
          prefix: ''
          suffix: ''
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: delete-package
        id: delete-package
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.KM_PAT_DELETE_PACKAGES }}
        run: |
          PACKAGE_NAME=${{ github.event.repository.name }}

          echo "[INFO] Attempting to delete package: $PACKAGE_NAME"

          if gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /orgs/${{ env.ORG_NAME }}/packages/container/$PACKAGE_NAME; then
            echo "[INFO] Package deleted successfully."
          else
            EXIT_CODE=$?
            if [[ "$EXIT_CODE" -eq 1 ]]; then
              echo "[WARN] Package '$PACKAGE_NAME' not found. Skipping delete."
            else
              echo "[ERROR] Failed to delete package '$PACKAGE_NAME' (exit code: $EXIT_CODE)"
              exit $EXIT_CODE
            fi
          fi
      - name: Disable this workflow
        shell: bash
        run: |
          gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
